In [1]:
import pandas as pd
import numpy as np
import nltk
import re
import string

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

from textblob import TextBlob
from wordcloud import WordCloud

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("mma_data_sherdog.csv")

df.head()

,Organization,Event,Date,Fight Number,Result,Fighter,Opponent,Method,Round,Time,Url
0,Ultimate Fighting Championship (UFC),UFC 219 - Cyborg vs. Holm,2017-12-30,0,win,"Cris ""Cyborg"" Justino",Holly Holm,Decision (Unanimous),5.0,5:00,http://www.sherdog.com/events/UFC-219-Cyborg-v...
1,Ultimate Fighting Championship (UFC),UFC 219 - Cyborg vs. Holm,2017-12-30,0,loss,Holly Holm,Cristiane Justino,Decision (Unanimous),5.0,5:00,http://www.sherdog.com/events/UFC-219-Cyborg-v...
2,Ultimate Fighting Championship (UFC),UFC 219 - Cyborg vs. Holm,2017-12-30,1,win,Khabib Nurmagomedov,Edson Barboza,Decision (Unanimous),3.0,5:00,http://www.sherdog.com/events/UFC-219-Cyborg-v...
3,Ultimate Fighting Championship (UFC),UFC 219 - Cyborg vs. Holm,2017-12-30,1,loss,Edson Barboza,Khabib Nurmagomedov,Decision (Unanimous),3.0,5:00,http://www.sherdog.com/events/UFC-219-Cyborg-v...
4,Ultimate Fighting Championship (UFC),UFC 219 - Cyborg vs. Holm,2017-12-30,2,win,Dan Hooker,Marc Diakiese,Submission (Guillotine Choke),3.0,0:42,http://www.sherdog.com/events/UFC-219-Cyborg-v...

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8958 entries, 0 to 8957
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Organization  8958 non-null   str
 1   Event         8958 non-null   str
 2   Date          8958 non-null   str
 3   Fight Number  8958 non-null   int64
 4   Result        8958 non-null   str
 5   Fighter       8958 non-null   str
 6   Opponent      8958 non-null   str
 7   Method        8958 non-null   str
 8   Round         8958 non-null   float64
 9   Time          8956 non-null   str
 10  Url           8958 non-null   str
dtypes: float64(1), int64(1), str(9)
memory usage: 2.4 MB

In [5]:
print(df.columns)

Index(['Organization', 'Event', 'Date', 'Fight Number', 'Result', 'Fighter',
       'Opponent', 'Method', 'Round', 'Time', 'Url'],
      dtype='str')

In [7]:
df.columns = df.columns.str.strip()
print(df.columns)

Index(['Organization', 'Event', 'Date', 'Fight Number', 'Result', 'Fighter',
       'Opponent', 'Method', 'Round', 'Time', 'Url'],
      dtype='str')

In [10]:
print(df.columns.tolist())

['Organization', 'Event', 'Date', 'Fight Number', 'Result', 'Fighter', 'Opponent', 'Method', 'Round', 'Time', 'Url']

In [12]:
print(df.columns)

Index(['Organization', 'Event', 'Date', 'Fight Number', 'Result', 'Fighter',
       'Opponent', 'Method', 'Round', 'Time', 'Url'],
      dtype='str')

In [20]:
df.head()

,Organization,Event,Date,Fight Number,Result,Fighter,Opponent,Method,Round,Time,Url
0,Ultimate Fighting Championship (UFC),UFC 219 - Cyborg vs. Holm,2017-12-30,0,win,"Cris ""Cyborg"" Justino",Holly Holm,Decision (Unanimous),5.0,5:00,http://www.sherdog.com/events/UFC-219-Cyborg-v...
1,Ultimate Fighting Championship (UFC),UFC 219 - Cyborg vs. Holm,2017-12-30,0,loss,Holly Holm,Cristiane Justino,Decision (Unanimous),5.0,5:00,http://www.sherdog.com/events/UFC-219-Cyborg-v...
2,Ultimate Fighting Championship (UFC),UFC 219 - Cyborg vs. Holm,2017-12-30,1,win,Khabib Nurmagomedov,Edson Barboza,Decision (Unanimous),3.0,5:00,http://www.sherdog.com/events/UFC-219-Cyborg-v...
3,Ultimate Fighting Championship (UFC),UFC 219 - Cyborg vs. Holm,2017-12-30,1,loss,Edson Barboza,Khabib Nurmagomedov,Decision (Unanimous),3.0,5:00,http://www.sherdog.com/events/UFC-219-Cyborg-v...
4,Ultimate Fighting Championship (UFC),UFC 219 - Cyborg vs. Holm,2017-12-30,2,win,Dan Hooker,Marc Diakiese,Submission (Guillotine Choke),3.0,0:42,http://www.sherdog.com/events/UFC-219-Cyborg-v...

In [22]:
df.columns

Index(['Organization', 'Event', 'Date', 'Fight Number', 'Result', 'Fighter',
       'Opponent', 'Method', 'Round', 'Time', 'Url'],
      dtype='str')

In [24]:
print(df.head())
print(df.columns.tolist())

                           Organization                      Event  \
0  Ultimate Fighting Championship (UFC)  UFC 219 - Cyborg vs. Holm
1  Ultimate Fighting Championship (UFC)  UFC 219 - Cyborg vs. Holm
2  Ultimate Fighting Championship (UFC)  UFC 219 - Cyborg vs. Holm
3  Ultimate Fighting Championship (UFC)  UFC 219 - Cyborg vs. Holm
4  Ultimate Fighting Championship (UFC)  UFC 219 - Cyborg vs. Holm

         Date  Fight Number Result                Fighter  \
0  2017-12-30             0    win  Cris "Cyborg" Justino
1  2017-12-30             0   loss             Holly Holm
2  2017-12-30             1    win    Khabib Nurmagomedov
3  2017-12-30             1   loss          Edson Barboza
4  2017-12-30             2    win             Dan Hooker

               Opponent                         Method  Round  Time  \
0            Holly Holm           Decision (Unanimous)    5.0  5:00
1     Cristiane Justino           Decision (Unanimous)    5.0  5:00
2        Edson Barboza            Decision (Unanimous)    3.0  5:00
3  Khabib Nurmagomedov            Decision (Unanimous)    3.0  5:00
4        Marc Diakiese   Submission (Guillotine Choke)    3.0  0:42

                                                 Url
0  http://www.sherdog.com/events/UFC-219-Cyborg-v...
1  http://www.sherdog.com/events/UFC-219-Cyborg-v...
2  http://www.sherdog.com/events/UFC-219-Cyborg-v...
3  http://www.sherdog.com/events/UFC-219-Cyborg-v...
4  http://www.sherdog.com/events/UFC-219-Cyborg-v...
['Organization', 'Event', 'Date', 'Fight Number', 'Result', 'Fighter', 'Opponent', 'Method', 'Round', 'Time', 'Url']

In [27]:
df.columns = df.columns.str.strip()

In [29]:
print(df.columns)
df.head()

Index(['Organization', 'Event', 'Date', 'Fight Number', 'Result', 'Fighter',
       'Opponent', 'Method', 'Round', 'Time', 'Url'],
      dtype='str')

,Organization,Event,Date,Fight Number,Result,Fighter,Opponent,Method,Round,Time,Url
0,Ultimate Fighting Championship (UFC),UFC 219 - Cyborg vs. Holm,2017-12-30,0,win,"Cris ""Cyborg"" Justino",Holly Holm,Decision (Unanimous),5.0,5:00,http://www.sherdog.com/events/UFC-219-Cyborg-v...
1,Ultimate Fighting Championship (UFC),UFC 219 - Cyborg vs. Holm,2017-12-30,0,loss,Holly Holm,Cristiane Justino,Decision (Unanimous),5.0,5:00,http://www.sherdog.com/events/UFC-219-Cyborg-v...
2,Ultimate Fighting Championship (UFC),UFC 219 - Cyborg vs. Holm,2017-12-30,1,win,Khabib Nurmagomedov,Edson Barboza,Decision (Unanimous),3.0,5:00,http://www.sherdog.com/events/UFC-219-Cyborg-v...
3,Ultimate Fighting Championship (UFC),UFC 219 - Cyborg vs. Holm,2017-12-30,1,loss,Edson Barboza,Khabib Nurmagomedov,Decision (Unanimous),3.0,5:00,http://www.sherdog.com/events/UFC-219-Cyborg-v...
4,Ultimate Fighting Championship (UFC),UFC 219 - Cyborg vs. Holm,2017-12-30,2,win,Dan Hooker,Marc Diakiese,Submission (Guillotine Choke),3.0,0:42,http://www.sherdog.com/events/UFC-219-Cyborg-v...

In [30]:
df.to_csv("mma_data_sherdog_nlp_processed.csv", index=False)