In [1]:
# Install if needed
# !pip install pandas scikit-learn nltk

import pandas as pd
import numpy as np

import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import re

In [2]:
df = pd.read_csv("ufc_event_data.csv")

df.head()

,event_id,event_name,event_date,event_city,event_state,event_country,event_url
0,665,UFC Fight Night: Dawson vs. Green,2023-10-07,Las Vegas,Nevada,USA,http://ufcstats.com/event-details/c8a49ff2acb6...
1,664,UFC Fight Night: Fiziev vs. Gamrot,2023-09-23,Las Vegas,Nevada,USA,http://ufcstats.com/event-details/c945adc22c2b...
2,663,UFC Fight Night: Grasso vs. Shevchenko 2,2023-09-16,Las Vegas,Nevada,USA,http://ufcstats.com/event-details/8fa2b0657236...
3,662,UFC 293: Adesanya vs. Strickland,2023-09-09,Sydney,New South Wales,Australia,http://ufcstats.com/event-details/ece280745f87...
4,661,UFC Fight Night: Gane vs. Spivac,2023-09-02,Paris,Ile-de-France,France,http://ufcstats.com/event-details/ef61d9f5176b...

In [3]:
df.info()
df.columns

<class 'pandas.DataFrame'>
RangeIndex: 665 entries, 0 to 664
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   event_id       665 non-null    int64
 1   event_name     665 non-null    str
 2   event_date     665 non-null    str
 3   event_city     665 non-null    str
 4   event_state    616 non-null    str
 5   event_country  665 non-null    str
 6   event_url      665 non-null    str
dtypes: int64(1), str(6)
memory usage: 109.4 KB

Index(['event_id', 'event_name', 'event_date', 'event_city', 'event_state',
       'event_country', 'event_url'],
      dtype='str')

In [5]:
print(df.columns)

Index(['event_id', 'event_name', 'event_date', 'event_city', 'event_state',
       'event_country', 'event_url'],
      dtype='str')

In [7]:
print(df.columns)

Index(['event_id', 'event_name', 'event_date', 'event_city', 'event_state',
       'event_country', 'event_url'],
      dtype='str')

In [8]:
df.head()

,event_id,event_name,event_date,event_city,event_state,event_country,event_url
0,665,UFC Fight Night: Dawson vs. Green,2023-10-07,Las Vegas,Nevada,USA,http://ufcstats.com/event-details/c8a49ff2acb6...
1,664,UFC Fight Night: Fiziev vs. Gamrot,2023-09-23,Las Vegas,Nevada,USA,http://ufcstats.com/event-details/c945adc22c2b...
2,663,UFC Fight Night: Grasso vs. Shevchenko 2,2023-09-16,Las Vegas,Nevada,USA,http://ufcstats.com/event-details/8fa2b0657236...
3,662,UFC 293: Adesanya vs. Strickland,2023-09-09,Sydney,New South Wales,Australia,http://ufcstats.com/event-details/ece280745f87...
4,661,UFC Fight Night: Gane vs. Spivac,2023-09-02,Paris,Ile-de-France,France,http://ufcstats.com/event-details/ef61d9f5176b...

In [11]:
print(df.columns)

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='str')

In [12]:
print(df.columns)

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='str')

In [15]:
print(data.head())

   event_id                                event_name  event_date event_city  \
0       665         UFC Fight Night: Dawson vs. Green  2023-10-07  Las Vegas
1       664        UFC Fight Night: Fiziev vs. Gamrot  2023-09-23  Las Vegas
2       663  UFC Fight Night: Grasso vs. Shevchenko 2  2023-09-16  Las Vegas
3       662          UFC 293: Adesanya vs. Strickland  2023-09-09     Sydney
4       661          UFC Fight Night: Gane vs. Spivac  2023-09-02      Paris

       event_state event_country  \
0           Nevada           USA
1           Nevada           USA
2           Nevada           USA
3  New South Wales     Australia
4    Ile-de-France        France

                                           event_url
0  http://ufcstats.com/event-details/c8a49ff2acb6...
1  http://ufcstats.com/event-details/c945adc22c2b...
2  http://ufcstats.com/event-details/8fa2b0657236...
3  http://ufcstats.com/event-details/ece280745f87...
4  http://ufcstats.com/event-details/ef61d9f5176b...

In [18]:
import pandas as pd

data = {
    "hours_studied": [1,2,3,4,5],
    "score": [50,55,65,70,80]
}

df = pd.DataFrame(data)

X = df[["hours_studied"]]
y = df["score"]

In [22]:
print(y.value_counts())

score
50    1
55    1
65    1
70    1
80    1
Name: count, dtype: int64

In [25]:
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

# Text preprocessing
def preprocess_text(text):
    text = text.lower()
    text = re.sub(r"[^a-z\s]", "", text)
    return text.strip()

# Example training data
texts = [
    "fighter dominated striking and won by knockout",
    "fighter secured takedowns and won by decision",
    "fighter was knocked out early",
    "fighter controlled grappling and submitted opponent"
]

labels = ["fighter1", "fighter1", "fighter2", "fighter1"]

# Preprocess training data
clean_texts = [preprocess_text(t) for t in texts]

# Create and fit vectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(clean_texts)

# Train model
model = LogisticRegression()
model.fit(X, labels)

# New fight prediction
new_fight = ["fighter dominated striking and finished with knockout"]

clean = preprocess_text(new_fight[0])
vec = vectorizer.transform([clean])

prediction = model.predict(vec)

print("Predicted Winner:", prediction[0])

Predicted Winner: fighter1