In [1]:
# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# NLP
from sklearn.feature_extraction.text import TfidfVectorizer

# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("mma_data_ufc.csv")

df.head()

,Event,Date,Location,Fight Number,Fighter,Record,Height,Weightclass,Reach,Leg Reach,Url
0,UFC Fight Night - Swanson vs Ortega,2017-12-09 00:00:00,"Fresno, California",0,Cub Swanson,25-8-0,"5' 8""",145,70.0,38.0,http://www.ufc.com/event/ufc-fight-night-fresn...
1,UFC Fight Night - Swanson vs Ortega,2017-12-09 00:00:00,"Fresno, California",0,Brian Ortega,"13-0-0, 1NC","5' 8""",145,69.0,39.0,http://www.ufc.com/event/ufc-fight-night-fresn...
2,UFC Fight Night - Swanson vs Ortega,2017-12-09 00:00:00,"Fresno, California",1,Jason Knight,20-4-0,"5' 10""",145,71.0,39.0,http://www.ufc.com/event/ufc-fight-night-fresn...
3,UFC Fight Night - Swanson vs Ortega,2017-12-09 00:00:00,"Fresno, California",1,Gabriel Benitez,20-7-0,"5' 8""",145,71.0,40.0,http://www.ufc.com/event/ufc-fight-night-fresn...
4,UFC Fight Night - Swanson vs Ortega,2017-12-09 00:00:00,"Fresno, California",2,Marlon Moraes,20-5-1,"5' 6""",135,67.0,37.0,http://www.ufc.com/event/ufc-fight-night-fresn...

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8928 entries, 0 to 8927
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Event         8928 non-null   str
 1   Date          8928 non-null   str
 2   Location      6148 non-null   str
 3   Fight Number  8928 non-null   int64
 4   Fighter       8928 non-null   str
 5   Record        8674 non-null   str
 6   Height        8928 non-null   str
 7   Weightclass   8928 non-null   int64
 8   Reach         6380 non-null   float64
 9   Leg Reach     4729 non-null   float64
 10  Url           8928 non-null   str
dtypes: float64(2), int64(2), str(7)
memory usage: 1.9 MB

In [4]:
# Drop missing rows
df = df.dropna()

# Remove duplicates
df = df.drop_duplicates()

df.shape

(4243, 11)

In [7]:
print(df.columns)

Index(['Event', 'Date', 'Location', 'Fight Number', 'Fighter', 'Record',
       'Height', 'Weightclass', 'Reach', 'Leg Reach', 'Url'],
      dtype='str')

In [9]:
df.columns = df.columns.str.strip()

In [12]:
df.head()

,Event,Date,Location,Fight Number,Fighter,Record,Height,Weightclass,Reach,Leg Reach,Url
0,UFC Fight Night - Swanson vs Ortega,2017-12-09 00:00:00,"Fresno, California",0,Cub Swanson,25-8-0,"5' 8""",145,70.0,38.0,http://www.ufc.com/event/ufc-fight-night-fresn...
1,UFC Fight Night - Swanson vs Ortega,2017-12-09 00:00:00,"Fresno, California",0,Brian Ortega,"13-0-0, 1NC","5' 8""",145,69.0,39.0,http://www.ufc.com/event/ufc-fight-night-fresn...
2,UFC Fight Night - Swanson vs Ortega,2017-12-09 00:00:00,"Fresno, California",1,Jason Knight,20-4-0,"5' 10""",145,71.0,39.0,http://www.ufc.com/event/ufc-fight-night-fresn...
3,UFC Fight Night - Swanson vs Ortega,2017-12-09 00:00:00,"Fresno, California",1,Gabriel Benitez,20-7-0,"5' 8""",145,71.0,40.0,http://www.ufc.com/event/ufc-fight-night-fresn...
4,UFC Fight Night - Swanson vs Ortega,2017-12-09 00:00:00,"Fresno, California",2,Marlon Moraes,20-5-1,"5' 6""",135,67.0,37.0,http://www.ufc.com/event/ufc-fight-night-fresn...

In [14]:
# Import libraries
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.datasets import load_iris

# Load a sample dataset (Iris)
data = load_iris()
X = data.data
y = data.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create the Decision Tree model
dt = DecisionTreeClassifier(random_state=42)

# Train the model
dt.fit(X_train, y_train)

# Make predictions
y_pred_dt = dt.predict(X_test)

# Evaluate the model
print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_dt))

Decision Tree Accuracy: 1.0

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

In [16]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Train the model
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)

# Predictions
y_pred_rf = rf_model.predict(X_test)

# Evaluation
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_rf))

Random Forest Accuracy: 1.0

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

In [19]:
print(len(features))
print(len(rf_model.feature_importances_))
print(type(features))

5
4
<class 'list'>

In [21]:
print(df.head())

                                 Event                 Date  \
0  UFC Fight Night - Swanson vs Ortega  2017-12-09 00:00:00
1  UFC Fight Night - Swanson vs Ortega  2017-12-09 00:00:00
2  UFC Fight Night - Swanson vs Ortega  2017-12-09 00:00:00
3  UFC Fight Night - Swanson vs Ortega  2017-12-09 00:00:00
4  UFC Fight Night - Swanson vs Ortega  2017-12-09 00:00:00

             Location  Fight Number          Fighter       Record  Height  \
0  Fresno, California             0      Cub Swanson       25-8-0   5' 8"
1  Fresno, California             0     Brian Ortega  13-0-0, 1NC   5' 8"
2  Fresno, California             1     Jason Knight       20-4-0  5' 10"
3  Fresno, California             1  Gabriel Benitez       20-7-0   5' 8"
4  Fresno, California             2    Marlon Moraes       20-5-1   5' 6"

   Weightclass  Reach  Leg Reach  \
0          145   70.0       38.0
1          145   69.0       39.0
2          145   71.0       39.0
3          145   71.0       40.0
4          135   67.0       37.0

                                                 Url
0  http://www.ufc.com/event/ufc-fight-night-fresn...
1  http://www.ufc.com/event/ufc-fight-night-fresn...
2  http://www.ufc.com/event/ufc-fight-night-fresn...
3  http://www.ufc.com/event/ufc-fight-night-fresn...
4  http://www.ufc.com/event/ufc-fight-night-fresn...

In [23]:
df.columns = df.columns.str.strip()

In [25]:
print(df.columns.tolist())

['Event', 'Date', 'Location', 'Fight Number', 'Fighter', 'Record', 'Height', 'Weightclass', 'Reach', 'Leg Reach', 'Url']